### ISSUE TITLE
Editor nondeterministically covers entire screen

### ISSUE THREAD

**Issue by steakknife** [niemeyer/hsandbox#30]

**Comment by steakknife** [comment]
![img](https://content.screencast.com/users/xzxzxzxx/folders/Jing/media/68d2b320-67e5-4c1c-b416-76de49199124/00000065.png)

**Comment by steakknife** [comment]
Must be a problem with the hsandbox runner python code or environment because manual tmux split windows work fine with other processes.

**Comment by steakknife** [comment]
Fixed in #15.

This needs to be merged ASAP.

**Comment by DavidP-sns** [comment]
I have the latest changes from master and am still experiencing this problem.
